### ISSUE TITLE
User can login to Parse Server and Authenticate with Spotify

### ISSUE THREAD

**Issue by uuilmer** [uuilmer/Pix#1]
* Create a dual-login screen
* Host on Heroku.
* Save user's Auth Token to make further requests.

**Comment by imxuyue** [comment]
I see you have completed this task. In the future, when you complete a task, could you attach a simple screenshot (if applicable) and the links to the associated commits?

**Comment by uuilmer** [comment]
* LoginActivity:
![107772895_621411571831324_6830734189597568152_n](https://user-images.githubusercontent.com/58693842/87473300-0f626000-c5d6-11ea-8d44-20be195da523.jpg)

Commits:
1. [https://github.com/uuilmer/Pix/commit/c960529d034d8030a85448fd43b9ce0ae42fe6d0](url)
1. [https://github.com/uuilmer/Pix/commit/d61dd085d3c3a7eefb86dd7beb02c29264fa1910](url)

**Comment by imxuyue** [comment]
Looks good! Thanks for the update.
